### PR TITLE
Added time in response

### PR DESCRIPTION
**Pull request by trusk89**
Added a separator and the actual latency in the response.

### CODE REVIEW

**Comment by Jameskmonger** [comment]
I'm not sure this looks great @trusk89:

    λ is-pokemon-go-up
    Yep. Go outside and catch some!|563

**Comment by trusk89** [comment]
@Jameskmonger yeah, but you can use split("|") to extract what interests you.

**Comment by sindresorhus** [comment]
Why? What's the use-case? If this is actually useful I think a flag that makes it only output the latency would be better.

**Comment by sotojuan** [comment]
Hi @trusk89! Thanks for taking the time to do this, but I think it'd be better as an option (verbose output) and I personally think it's not necessary as the code for this is simple/dumb and times out after three seconds anyway—you can check the time limits to approximate. I'm going to close this for now but may consider it in the future!

Sorry for the late reply!

**Comment by trusk89** [comment]
No problem!

-- --

*"Nu lasa nimic intre tine si visele tale."*
--
<http://www.blog.alexbartis.com>

*Alex Bartis, *
iOS Developer @ Fortech

www.bartis.ro | facebook.com/bartis.alex | twitter.com/alexbartis

**Pull request closed without merging**
